### ISSUE TITLE
Qoin Expenditure

### ISSUE THREAD

**Issue by vibronicshark55** [toosuto-r/qchat#24]
Looks like bot functions currently handled spending qoin individually, perhaps a wrapper function is required which could be used by all bots/requests.

**Comment by toosuto-r** [comment]
See ptcst and ptchk in pts.q - this seems to have the functionality you want? It's called in chatter with fchk, to check the user can do the action before allowing anything through.

**Comment by vibronicshark55** [comment]
That's probably it, ill have a look tomorrow.

**Comment by vibronicshark55** [comment]
Thats it.
