### ISSUE TITLE
Repeated code sections

### ISSUE THREAD

**Issue by vibronicshark55** [toosuto-r/qchat#3]
Code wrapped like this appears quite often:
```
ucol[.z.u;0],string[z],ucol[.z.u;1]
```

Could probably be replaced with a single function:
```
ucolw:{ucol[x;0],y,ucol[x;1]}
ucolw[.z.u;"some text"]
```

Additionally the 'return' functionality is repeated quite often too:
```
neg[value[aw]]@'0,'ccache[key[aw]]@'uvol[key aw]
neg[aw z]@0,ccache[z]
```
Could also be wrapped up in `all` and `current user` type functions.

I can do up a PR if you think it is worthwhile.

**Comment by toosuto-r** [comment]
Yeah this is nasty, but the tidying is partly done locally - been meaning to finish it up, will just continue with that, thanks!

**Comment by toosuto-r** [comment]
Latest commit addresses the return to client functions where behaviour is not unique, as in one instance in .c4 - this can be amended later if necessary. Colour wrapped also added.

**Comment by vibronicshark55** [comment]
Looks solid, I'm going to close this issue.
